 
server:
  port: 2221

eureka:
  client:
    enabled: true
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

controller:
  base-path: /crud
  insert-data: /insert-data-customer
  get-data: /get-data-customer

feign-url:
  host: REPOSITORY-H2
  feign-insert-data: /repository/insert-data
  feign-get-data: /repository/get-data
         